### ISSUE TITLE
Issue with running CNN_StressNet

### ISSUE THREAD

**Issue by yugushihuang** [zhenguonie/stress_net#1]
Hi @zhenguonie,

Thank you very much for sharing your work. I am able to run the SCSNet with the data and code you provided. However, for the stressnet, I use the "all_data_m.npy" and the result is pretty bad. I notice that you use "all_data_m2.0_train_padded.npy" and "all_data_m2.0_test_padded.npy" but I am unable to find the data from the link you provided. Could you please provide the data link of this two so I can try out the Stress Net snippet?

Thanks&Regards,
Tinker

**Comment by zhenguonie** [comment]
Thanks for your attention. We have updated the code. Please check it out again.

**Comment by yugushihuang** [comment]
Hi @zhenguonie,

Thank you very much for updating the code. However, I execute the new "CNN_StressNet.py" with the downloaded "all_data_m.npy". The result still all zero. Is that because the input image in "all_data_m.npy" is 32*32 but your algorithm set the resolution to 24*32?

Thanks!
Tinker

**Comment by zhenguonie** [comment]
All the input image is 24*32. Did you run the code on a GPU? If on the CPU, you may change the code.

**Comment by yugushihuang** [comment]
Hi @zhenguonie ,

I run it from GPU. But I look at the data on "all_data_m.npy", the image size is 32*32. 

Thanks,
Tinker

**Comment by zhenguonie** [comment]
I am sure that the image is 24*32.

Please use tensorflow 1.4 version. I write my code with tf1.4.

Also, I update the code to GitHub again and run it. It looks good.

**Comment by yugushihuang** [comment]
Sorry for the late close.

Thanks for all the response, it is really helpful!
